# Generated by Django 5.2.3 on 2025-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_post_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='context',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
